// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PP.Data.Context;

#nullable disable

namespace PP.Data.Migrations
{
    [DbContext(typeof(MyDataContext))]
    partial class MyDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PP.Core.Domain.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idprojeto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("idpessoa");

                    b.HasKey("Id")
                        .HasName("pk_membros_projeto");

                    b.HasIndex("PessoaId");

                    b.ToTable("membros", (string)null);
                });

            modelBuilder.Entity("PP.Core.Domain.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datanascimento");

                    b.Property<bool>("IsFuncionario")
                        .HasColumnType("boolean")
                        .HasColumnName("funcionario");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("pessoa", (string)null);
                });

            modelBuilder.Entity("PP.Core.Domain.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime>("DataPrevisaoFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_previsao_fim");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<double>("Orcamento")
                        .HasColumnType("double precision")
                        .HasColumnName("orcamento");

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("idgerente");

                    b.Property<string>("Risco")
                        .HasColumnType("text")
                        .HasColumnName("risco");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("projeto", (string)null);
                });

            modelBuilder.Entity("PP.Core.Domain.Membro", b =>
                {
                    b.HasOne("PP.Core.Domain.Pessoa", "Pessoa")
                        .WithMany("Membro")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membros_pessoa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("PP.Core.Domain.Projeto", b =>
                {
                    b.HasOne("PP.Core.Domain.Pessoa", "Pessoa")
                        .WithMany("Projeto")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gerente");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("PP.Core.Domain.Pessoa", b =>
                {
                    b.Navigation("Membro");

                    b.Navigation("Projeto");
                });
#pragma warning restore 612, 618
        }
    }
}
